import type { LegalDocument } from '@/types';
import { COMPANY } from '@/data/company';

const LAST_UPDATED = '23 September 2026';
const ADDRESS = `${COMPANY.address.line1}, ${COMPANY.address.line2}, ${COMPANY.address.state} ${COMPANY.address.pin}, ${COMPANY.address.country}`;

export const TERMS: LegalDocument = {
  title: 'Terms of Service',
  summary: `These terms govern your use of the ${COMPANY.name} website and of our products and services, including the Health-Care-Tracking Engine, One-Touch-Service, Gesher Trade and our DevOps & Cloud engineering services.`,
  lastUpdated: LAST_UPDATED,
  sections: [
    {
      heading: '1. Acceptance of these terms',
      paragraphs: [
        `By accessing this website or using any ${COMPANY.name} product or service, you agree to these Terms of Service. If you are using our services on behalf of an organisation, you confirm that you are authorised to accept these terms for that organisation.`,
        'Separate written agreements (such as a master services agreement or statement of work) take precedence over these terms where they conflict.',
      ],
    },
    {
      heading: '2. Our services',
      bullets: [
        'Health-Care-Tracking Engine — software that helps clinical laboratories and diagnostic centres track test histories and send checkup reminders to their patients.',
        'One-Touch-Service — a platform that connects customers with independent skilled and unskilled workers.',
        'Gesher Trade — a peer-to-peer marketplace where independent buyers and sellers list and trade goods.',
        'DevOps, cloud and custom software engineering delivered under a separate engagement agreement.',
      ],
    },
    {
      heading: '3. Accounts and acceptable use',
      paragraphs: ['You are responsible for keeping your credentials confidential and for all activity under your account. You agree not to:'],
      bullets: [
        'use the services for any unlawful, fraudulent or misleading purpose;',
        'upload malware, attempt unauthorised access or disrupt the integrity or performance of our systems;',
        'post false listings, impersonate others or misrepresent your identity, skills or goods;',
        'send unsolicited messages to patients, workers or users through our messaging channels.',
      ],
    },
    {
      heading: '4. Marketplaces and independent parties',
      paragraphs: [
        'Workers on One-Touch-Service and sellers on Gesher Trade are independent parties, not employees or agents of Gesher Technologies. We verify identity where indicated, but we do not guarantee the quality, safety or legality of work performed or goods sold.',
        'Escrow alerts and verification badges are risk-reduction tools. Buyers and customers remain responsible for inspecting goods and agreeing terms directly with the other party.',
      ],
    },
    {
      heading: '5. Healthcare data',
      paragraphs: [
        'Laboratories using the Health-Care-Tracking Engine remain the data fiduciary for their patients’ information and are responsible for obtaining the consent required to send reminders. Gesher Technologies processes that data only on the laboratory’s instructions, as described in our Privacy Policy and the applicable data processing agreement.',
        'Reminders generated by our software are informational. They are not medical advice and do not replace consultation with a qualified doctor.',
      ],
    },
    {
      heading: '6. Fees and payment',
      paragraphs: [
        'Fees for subscriptions and engineering services are set out in the relevant quotation or agreement. Unless stated otherwise, fees are exclusive of GST, which will be charged at the applicable rate.',
      ],
    },
    {
      heading: '7. Intellectual property',
      paragraphs: [
        `The website, software, trademarks and content provided by ${COMPANY.name} are owned by us or our licensors. Ownership of deliverables from custom engineering work is governed by the relevant agreement. You retain ownership of the data you submit to our services.`,
      ],
    },
    {
      heading: '8. Availability and changes',
      paragraphs: [
        'We work to keep our services available and secure, but we do not guarantee uninterrupted operation. Service levels, where offered, are defined in your agreement. We may update features or these terms; material changes will be announced on this website with a new “last updated” date.',
      ],
    },
    {
      heading: '9. Limitation of liability',
      paragraphs: [
        `To the maximum extent permitted by law, ${COMPANY.name} is not liable for indirect, incidental or consequential losses, or for loss of profits, revenue or data. Our total liability for any claim relating to the services is limited to the fees you paid to us for the relevant service in the twelve months before the claim arose.`,
      ],
    },
    {
      heading: '10. Governing law',
      paragraphs: [
        'These terms are governed by the laws of India. The courts at Ernakulam, Kerala have exclusive jurisdiction over any dispute arising from them.',
      ],
    },
    {
      heading: '11. Contact',
      paragraphs: [`Questions about these terms can be sent to ${COMPANY.email} or by post to ${COMPANY.name}, ${ADDRESS}.`],
    },
  ],
};

export const PRIVACY: LegalDocument = {
  title: 'Privacy Policy',
  summary: `This policy explains what personal data ${COMPANY.name} collects, why we collect it, and the choices you have. We process personal data in line with India’s Digital Personal Data Protection Act, 2023 (DPDP Act).`,
  lastUpdated: LAST_UPDATED,
  sections: [
    {
      heading: '1. Who we are',
      paragraphs: [
        `${COMPANY.name} (“we”, “us”) is based at ${ADDRESS}. For personal data you give us directly — for example through our contact form — we act as the data fiduciary.`,
        'For patient data processed in the Health-Care-Tracking Engine, the laboratory or diagnostic centre is the data fiduciary and we act as its data processor.',
      ],
    },
    {
      heading: '2. Data we collect',
      bullets: [
        'Contact details you submit: your name, WhatsApp number and message, and — if you choose to share them — your email address and company name.',
        'Account and profile information for platform users, such as worker skills, service areas, ratings and marketplace listings.',
        'Patient information that laboratories upload, such as names, contact numbers, test types and due dates for follow-up checkups.',
        'Technical data such as device type, browser and basic usage logs used to keep our services secure and reliable.',
      ],
    },
    {
      heading: '3. How we use data',
      bullets: [
        'To respond to enquiries, schedule demos and provide quotations.',
        'To operate our platforms — for example, delivering service requests to workers or reminders to patients on behalf of laboratories.',
        'To verify identities and prevent fraud on One-Touch-Service and Gesher Trade.',
        'To maintain security, troubleshoot issues and improve our products.',
        'To meet legal, tax and regulatory obligations.',
      ],
      paragraphs: ['We do not sell personal data, and we do not use patient health data for advertising.'],
    },
    {
      heading: '4. Consent and your rights',
      paragraphs: ['Where we rely on consent, you may withdraw it at any time. Under the DPDP Act you have the right to:'],
      bullets: [
        'access a summary of the personal data we hold about you and how it is processed;',
        'request correction, completion, updating or erasure of your personal data;',
        'have your grievances redressed; and',
        'nominate another person to exercise your rights in the event of death or incapacity.',
      ],
    },
    {
      heading: '5. Sharing',
      paragraphs: [
        'We share personal data only with service providers who help us run our services — such as cloud hosting, SMS, WhatsApp Business and email delivery providers — under contracts that require them to protect it, or where the law requires us to.',
      ],
    },
    {
      heading: '6. Security and retention',
      paragraphs: [
        'Data is encrypted in transit and at rest, access is restricted by role, and access to production systems is logged. We keep personal data only for as long as needed for the purposes above or as required by law, after which it is deleted or anonymised.',
      ],
    },
    {
      heading: '7. Cookies and local storage',
      paragraphs: [
        'This website does not use advertising or tracking cookies. It may use your browser’s local storage to remember interface preferences and to keep a copy of a form submission on your own device.',
      ],
    },
    {
      heading: '8. Children',
      paragraphs: [
        'Our services are not directed at children. Where a laboratory processes a child’s data, it is responsible for obtaining verifiable consent from a parent or lawful guardian.',
      ],
    },
    {
      heading: '9. Changes to this policy',
      paragraphs: ['We may update this policy from time to time. The “last updated” date at the top shows when it was last revised.'],
    },
    {
      heading: '10. Grievance officer',
      paragraphs: [
        `For privacy questions, requests or complaints, contact our Grievance Officer at ${COMPANY.privacyEmail} or write to ${COMPANY.name}, ${ADDRESS}. We will acknowledge your request promptly and respond within the time required by law.`,
      ],
    },
  ],
};
